<?php
/**
 * @file
 */

// Drupal needs this blank file.

/**
 * Implements hook_ctools_plugin_api().
 */
function humanitarianresponse_documents_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function humanitarianresponse_documents_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implements hook_enable()
 */
function humanitarianresponse_documents_enable() {
  
}
